### ISSUE TITLE
Fix email notifications

### ISSUE THREAD

**Issue by cryptodani** [AragonBlack/fundraising#128]
When configuring 0.8 Camino email notifications the tap and market marker permission updates can be made subject to an email notification but Fundraising app doesn't appear.

Also clicking on a permission (at least on my machine) and then on "subscribe" nothing happens

**Comment by osarrouy** [comment]
That's because there are no events actually emitted by the Fundraising contract as such ... These events are emitted by the Presale, MarketMaker or Tap contracts so these are the only ones you can subscribe too ...

Regarding the the error on hitting the subscribe button this is a thing which is entirely handled by the Aragon Client [not our apps] so may wanna open the issue there instead.

Closing this one in the meanwhile.

**Comment by cryptodani** [comment]
Good news! Now thats the template has been merged to apm repo it works :)
