### ISSUE TITLE
Cannot run it

### ISSUE THREAD

**Issue by luisivan** [AragonBlack/fundraising#25]
I think a package is not in the npm registry, and therefore `npm i` fails. Looking forward to trying this out!

> '@ablack/fundraising-formula-bancor@^0.1.0' is not in the npm registry.

**Comment by deamme** [comment]
Hey! Sorry for the late reply. You can try out just the frontend if you go to the following branch https://github.com/AragonBlack/fundraising/tree/overview-tab and then in the following folder https://github.com/AragonBlack/fundraising/tree/overview-tab/apps/controller-aragon-fundraising/app run `npm install` and after that run the start script `npm run start`.

**Comment by osarrouy** [comment]
@luisivan I mark this issue as closed. Let us know / re-open if you have any more questions ! :)

**Comment by luisivan** [comment]
Thanks! Tried it out and it's beautiful!

**Comment by fredfortier** [comment]
@deamme Do you have some slightly more detailed instructions for trying the frontend? Here is what I get after naively following your instructions above: `Uncaught RangeError: Use `yyyy` instead of `YYYY` for formating years; see`. I'm probably missing something obvious. Any pointers would be appreciated.

**Comment by deamme** [comment]
@fredfortier I've just fixed that issue. Can you pull the newest changes and try again?
