### ISSUE TITLE
Improve UI to streamline the open and claim process

### ISSUE THREAD

**Issue by john-light** [AragonBlack/fundraising#58]
Currently it takes three txs for each buy order:

1. Approval
2. Place order
3. Claim order

This is a lot of txs that will place a lot of load on the blockchain when multiplied by many users. I challenge you to reduce the number of txs / gas / blockchain data necessary to place orders :)

**Comment by osarrouy** [comment]
Hey @john-light,

Thanks a lot for your feedbacks.

 I'm not sure to understand what @lkngtn says but to make it clear: each user MUST claim it's own order [the clearing step which was in an older version of the contract was shared between orders but we found a way to remove it to gain at least one transaction ...].

Unfortunately this 'buy and claim' situation can't really be circumvented due to the batching of orders. I've thought about it a little and I think the best we could do would be to improve the UI in a next version to be guided between the two transactions [like in the new ENS manager where you have a spinner asking you to wait for a couple of seconds before you can finalize the purchase of your ENS name].

This would not solve the basis of the issue [the need for two transactions if we wanna batch orders] but would provide a cleaner interaction pattern for the user.

When it comes to the pre `Approve` transaction I agree we should find a way to ditch this one. Unfortunately this is something which is implemented at the Aragon Client level for the security reason @lkngtn has mentionned.

I'll see with Brett if we can improve this at some point ...

**Comment by john-light** [comment]
> Unfortunately this 'buy and claim' situation can't really be circumvented due to the batching of orders. I've thought about it a little and I think the best we could do would be to improve the UI in a next version to be guided between the two transactions [like in the new ENS manager where you have a spinner asking you to wait for a couple of seconds before you can finalize the purchase of your ENS name].

If it's not possible to reduce blockchain load by reducing the number of txs, at least the UX of the tx flow could be improved and I think something like this would certainly help!

FWIW if the current number of txs is absolutely required for security and technical reasons then I would leave as-is and just focus on improving the UX of the tx flow.

**Comment by arsenyjin** [comment]
Did you guys think to implementing meta transactions, like GSN for example?

**Comment by osarrouy** [comment]
@arsenyjin This is about to be implemented as a core feature of aragonOS so yes :)

Though i'm not sure it makes a lot of sense for a market-making application where you need tokens to spend anyhow ...

**Comment by osarrouy** [comment]
Moved to #179.
