### ISSUE TITLE
Add user defined max slippage

### ISSUE THREAD

**Issue by cryptodani** [AragonBlack/fundraising#92]
Right now max slippage for a batch is 20%, for "trader" type users this may be too much and having a way for the user to decide on the max slippage would attract a larger user base than hodlers and encourage arbitraging

**Comment by osarrouy** [comment]
Unfortunately there is no way to easily enforce a per-user slippage control over a batch [because of Solidity's limitations]. The best we can do is enforce price slippage control over the whole batch [which is already implemented].

I think the overall idea of implementing batching is to incentivize slow trading anyhow and so avoid 'traditionnal' trading behavior.
